// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBwvLgN5hh_YpIOdSbLdKvIaqX3d0wq4d8',
//     appId: '1:24632069950:android:e34a25771350f1eb60e66f',
//     messagingSenderId: '24632069950',
//     projectId: 'faisal-tv-dac7d',
//     storageBucket: 'faisal-tv-dac7d.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBlkFp0yeh128-2vxDvGhxY4UU9jL6Km8w',
//     appId: '1:24632069950:ios:6b1a17c74086f98060e66f',
//     messagingSenderId: '24632069950',
//     projectId: 'faisal-tv-dac7d',
//     storageBucket: 'faisal-tv-dac7d.firebasestorage.app',
//     iosBundleId: 'com.example.hTv',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBlkFp0yeh128-2vxDvGhxY4UU9jL6Km8w',
//     appId: '1:24632069950:ios:6b1a17c74086f98060e66f',
//     messagingSenderId: '24632069950',
//     projectId: 'faisal-tv-dac7d',
//     storageBucket: 'faisal-tv-dac7d.firebasestorage.app',
//     iosBundleId: 'com.example.hTv',
//   );
// }
